### ISSUE TITLE
Import "node-fetch" instead of "fetch"?

### ISSUE THREAD

**Issue by jaarenhoevel** [btastic/MMM-moonraker#3]
After adding this module, it won't start because it can't import `fetch`. Installing `fetch` via npm doesn't solve the problem because it doesn't provide the functionality needed. 
Changing the require in `node-helper.js` from `fetch` to `node-fetch` solves the problem for me.

**Comment by btastic** [comment]
Not sure what exactly changed in the main project, but `fetch` used to be an alias that was pointing to `node-fetch`. The `node-fetch` requirement comes from the main magic mirror project

**Comment by jaarenhoevel** [comment]
It could also be that I am using an older version of MMM. I will see if the problem persists with the latest version of MMM.
